"""Minimal music and sound-effect polish.

Five things, placed rarely:

* a **riser** into a moment the episode has been building towards,
* a **hit** on a fail or a reveal, at the frame it lands,
* a **whoosh** on a real transition -- a change of place or of source file,
* an **ambience or music bed** under a stretch, when the style allows one,
* a **silence drop**: everything out for a beat, so the next thing lands.

## The two rules that do the work

**A cue names the moment it is for.** There is no "place one at every cut"
path. A candidate is generated by something the earlier passes recorded -- a
death screen, a payoff beat, an environment change -- and a cue with nothing
behind it is refused as ``no_moment`` rather than placed hopefully.

**A cue may not land on a word.** Hits, risers and whooshes are checked against
the transcript with a guard band either side, because a sting over the middle
of a sentence is the single most obvious way an automated edit announces
itself. Beds are the exception and are ducked instead -- and the plan says so
in the cue's own safety notes rather than in a footnote.

## What it does not do

Nothing here plays a sound. In ``placeholders`` mode no library is read at all
and every cue is a note; in ``assets`` mode the Session 6 matcher is asked, and
anything it cannot satisfy stays a note and lands on the shopping list. Levels
are never measured, loops are never checked for a clean seam, and no cue is
ever executed by this package.
"""
from __future__ import annotations

from typing import Optional, Sequence

from editing.polish.schema import (
    CUE_REQUIREMENT, SFX_KINDS, AudioCue, AudioPolishConfig, AudioPolishPlan,
    allowed_cue_kinds, cue_id_for, now,
)
from editing.roughcut.schema import RoughCutPlan
from editing.schema import StructureTimeline, TimelineSegment
from editing.style.presets import StylePreset

#: Seconds before a moment that a riser starts. Long enough to be a build,
#: short enough that it does not sit under the previous section.
RISER_LEAD = 3.0

#: How long a hit occupies. A one-shot; the number is for the plan's arithmetic
#: rather than a claim about any particular file.
HIT_SECONDS = 1.2

#: How long a whoosh occupies, straddling the cut.
WHOOSH_SECONDS = 0.8

#: How long everything drops out for, before a moment lands.
SILENCE_SECONDS = 0.6

#: Importance levels that can earn a hit.
HIT_IMPORTANCE = frozenset({"payoff", "reveal", "danger"})

#: Importance levels a riser may build into.
RISER_IMPORTANCE = frozenset({"payoff", "reveal"})

#: A clip shorter than this is too short to carry a cue of its own.
MIN_CLIP_SECONDS = 2.0

#: A bed needs a stretch at least this long to be worth laying.
MIN_BED_SECONDS = 20.0


def build_audio_plan(
    timeline: StructureTimeline,
    cut: RoughCutPlan,
    style: StylePreset,
    config: AudioPolishConfig,
    *,
    library=None,
    name: str = "structure",
) -> AudioPolishPlan:
    """Every cue this pass considered, accepted and refused together.

    ``library`` is an optional ``AssetLibrary``. It is read only in ``assets``
    mode; in ``placeholders`` mode it is ignored entirely, so a run with no
    library produces exactly the same plan.
    """
    config = config.validated()
    plan = AudioPolishPlan(
        name=name,
        mode=config.mode,
        config=config,
        style=style.name,
        sequence_name=cut.sequence_name,
        cut_duration=round(cut.total_duration, 3),
        generated_at=now(),
        warnings=list(config.warnings),
    )

    if not config.enabled:
        plan.safety_notes.append(
            "No cue was considered: audio polish is off for this run."
        )
        return plan

    allowed = allowed_cue_kinds(style)
    speech = _speech_spans(timeline, cut)
    candidates = _candidates(timeline, cut, config)

    for cue in candidates:
        if cue.kind not in allowed:
            _reject(cue, "style_forbids",
                    f"the {style.name} style does not use {cue.kind} cues")
            continue
        if cue.kind == "music_bed" and not config.music_bed:
            _reject(cue, "bed_not_allowed",
                    "a music or ambience bed is not allowed for this run")
            continue
        if cue.priority < config.min_priority:
            _reject(cue, "no_moment",
                    f"scored {cue.priority:.2f}, below the "
                    f"{config.min_priority:.2f} a cue needs to be placed")
            continue
        if cue.kind in SFX_KINDS or cue.kind == "silence_drop":
            overlap = _covers_speech(cue, speech, config.speech_guard)
            if overlap is not None:
                _reject(cue, "would_cover_speech",
                        f"a line is being spoken at {overlap:.1f}s and a "
                        f"{cue.kind} there would land on it")
                continue

    _apply_budget(candidates, config, plan)

    if config.uses_library:
        _resolve_assets(candidates, library, plan)
    else:
        for cue in candidates:
            if cue.accepted:
                cue.placeholder_only = True
                cue.safety_notes.append(
                    "placeholder only: no library was read for this run")

    _finish(plan, candidates, config)
    return plan


# ---------------------------------------------------------------------------
# Candidates
# ---------------------------------------------------------------------------

def _candidates(
    timeline: StructureTimeline,
    cut: RoughCutPlan,
    config: AudioPolishConfig,
) -> list[AudioCue]:
    """Everything this pass can argue for, before any rule refuses it."""
    out: list[AudioCue] = []
    moments = _moments(timeline, cut)

    for moment in moments:
        out.extend(_cues_for_moment(moment))

    out.extend(_transition_cues(cut))
    out.extend(_bed_cues(cut, config))

    out.sort(key=lambda cue: (cue.start, cue.kind))
    return out


class _Moment:
    """One thing worth marking, resolved onto the cut."""

    def __init__(self, at: float, segment: TimelineSegment, placement,
                 kind: str, why: str, strength: float):
        self.at = at
        self.segment = segment
        self.placement = placement
        self.kind = kind          # "payoff" / "reveal" / "death" / "danger"
        self.why = why
        self.strength = strength


def _moments(timeline: StructureTimeline, cut: RoughCutPlan) -> list[_Moment]:
    """Where the earlier passes said something lands, in sequence time."""
    from editing.roughcut.select import map_to_sequence

    out: list[_Moment] = []
    for segment in timeline.segments:
        importance = segment.importance
        death = any(getattr(event.ui, "death_screen", False)
                    for event in segment.events)
        reaction = segment.audio_reaction

        if not death and importance not in HIT_IMPORTANCE:
            continue

        # Where the moment actually lands, not where the segment starts. A
        # segment is eight seconds of footage; the scream inside it is the
        # frame a sting belongs on, and marking the segment boundary instead
        # would put every cue up to eight seconds early.
        source_at = segment.start
        if death:
            source_at = min(
                (event.start for event in segment.events
                 if getattr(event.ui, "death_screen", False)),
                default=segment.start)
        elif reaction is not None:
            source_at = reaction.start

        at = map_to_sequence(cut.placements, segment.asset_id, source_at)
        if at is None:
            at = map_to_sequence(
                cut.placements, segment.asset_id, segment.start)
        if at is None:
            continue
        placement = cut.placement_at(at)

        if death:
            out.append(_Moment(
                at, segment, placement, "death",
                "a death screen is on screen here", 0.85))
            continue
        strength = 0.55 + min(0.25, segment.usefulness * 0.25)
        if reaction is not None:
            strength = min(1.0, strength + 0.12)
        out.append(_Moment(
            at, segment, placement, importance,
            f"the picture here is a {importance}"
            + (f" and the audio spikes ({reaction.type})"
               if reaction is not None else ""),
            strength))
    return out


def _cues_for_moment(moment: _Moment) -> list[AudioCue]:
    """The cues one moment could justify. Usually one, sometimes two."""
    out: list[AudioCue] = []
    short_clip = (
        moment.placement is not None
        and moment.placement.sequence_duration < MIN_CLIP_SECONDS
    )

    hit = AudioCue(
        cue_id=cue_id_for("hit", moment.at),
        kind="hit",
        start=round(moment.at, 3),
        end=round(moment.at + HIT_SECONDS, 3),
        target=f"the {moment.kind} at {moment.at:.1f}s",
        moment="death_or_fail" if moment.kind == "death" else (
            "reveal" if moment.kind == "reveal" else (
                "payoff_line" if moment.kind == "payoff" else "danger")),
        placement_id=(moment.placement.placement_id
                      if moment.placement else ""),
        segment_id=moment.segment.segment_id,
        priority=round(moment.strength, 3),
        reason=f"a sting marks the moment: {moment.why}",
        placeholder=("a hard one-shot for a fail" if moment.kind == "death"
                     else "a hard one-shot sting"),
        evidence=[moment.why],
    )
    if short_clip:
        _reject(hit, "clip_too_short",
                f"the clip under this moment is "
                f"{moment.placement.sequence_duration:.1f}s, too short to "
                "carry a sting cleanly")
    out.append(hit)

    if moment.kind in RISER_IMPORTANCE and moment.at >= RISER_LEAD:
        out.append(AudioCue(
            cue_id=cue_id_for("riser", moment.at - RISER_LEAD),
            kind="riser",
            start=round(moment.at - RISER_LEAD, 3),
            end=round(moment.at, 3),
            target=f"the {moment.kind} at {moment.at:.1f}s",
            moment="reveal" if moment.kind == "reveal" else "payoff_line",
            placement_id=(moment.placement.placement_id
                          if moment.placement else ""),
            segment_id=moment.segment.segment_id,
            priority=round(max(0.0, moment.strength - 0.08), 3),
            reason=f"a build into the {moment.kind} three seconds later",
            placeholder="a riser or build, about three seconds",
            evidence=[moment.why],
        ))

    if moment.kind in ("reveal", "death") and moment.at >= SILENCE_SECONDS:
        out.append(AudioCue(
            cue_id=cue_id_for("silence_drop", moment.at - SILENCE_SECONDS),
            kind="silence_drop",
            start=round(moment.at - SILENCE_SECONDS, 3),
            end=round(moment.at, 3),
            target=f"the {moment.kind} at {moment.at:.1f}s",
            moment="reveal" if moment.kind == "reveal" else "death_or_fail",
            placement_id=(moment.placement.placement_id
                          if moment.placement else ""),
            segment_id=moment.segment.segment_id,
            priority=round(max(0.0, moment.strength - 0.15), 3),
            reason="everything out for half a second, so the moment lands",
            placeholder="",
            evidence=[moment.why],
        ))
    return out


def _transition_cues(cut: RoughCutPlan) -> list[AudioCue]:
    """A whoosh only where there is a real transition.

    "Real" means the cut moves to a different source file, which is the one
    boundary this layer can see without guessing: two clips from the same
    recording are a trim, and marking a trim with a whoosh is exactly the spam
    this pass exists not to produce.
    """
    out: list[AudioCue] = []
    previous = None
    for placement in cut.placements:
        if previous is not None and placement.asset_id != previous.asset_id:
            at = placement.sequence_start
            cue = AudioCue(
                cue_id=cue_id_for("whoosh", at),
                kind="whoosh",
                start=round(max(0.0, at - WHOOSH_SECONDS / 2), 3),
                end=round(at + WHOOSH_SECONDS / 2, 3),
                target=f"the change of source at {at:.1f}s",
                placement_id=placement.placement_id,
                priority=0.55,
                reason="the cut moves to a different recording here, which a "
                       "viewer reads as a section change",
                placeholder="a short transition whoosh",
                evidence=[f"clip {previous.placement_id} -> "
                          f"{placement.placement_id}"],
            )
            if placement.sequence_duration < MIN_CLIP_SECONDS:
                _reject(cue, "clip_too_short",
                        f"the clip after this transition is "
                        f"{placement.sequence_duration:.1f}s")
            out.append(cue)
        previous = placement
    return out


def _bed_cues(
    cut: RoughCutPlan, config: AudioPolishConfig
) -> list[AudioCue]:
    """At most one bed, under the whole cut.

    One rather than several on purpose. Deciding where a piece of music should
    start and stop is a creative call this layer has no evidence for, and a
    dozen bed segments would be a dozen guesses. One bed under the episode is a
    single, obvious, easily-refused proposal.
    """
    duration = cut.total_duration
    if duration < MIN_BED_SECONDS:
        return [_bed(0.0, duration, config, refused=(
            "clip_too_short",
            f"the cut is {duration:.0f}s, shorter than the {MIN_BED_SECONDS:.0f}s "
            "a bed needs to be worth laying"))]

    end = min(duration, config.max_bed_seconds)
    cue = _bed(0.0, end, config)
    if end < duration:
        cue.safety_notes.append(
            f"the bed stops at {end:.0f}s of a {duration:.0f}s cut; a longer "
            "one would need a second piece of music rather than a longer loop")
    return [cue]


def _bed(start: float, end: float, config: AudioPolishConfig,
         *, refused: Optional[tuple] = None) -> AudioCue:
    cue = AudioCue(
        cue_id=cue_id_for("music_bed", start),
        kind="music_bed",
        start=round(start, 3),
        end=round(end, 3),
        target="the whole cut",
        priority=0.55,
        reason="a bed under the episode, ducked under the commentary",
        placeholder="a loopable low-intensity bed",
        evidence=[f"{end - start:.0f}s of cut"],
    )
    if config.ducking:
        cue.safety_notes.append(
            "the plan asks for this to duck under speech; the amount is not "
            "measured and has to be set by ear")
    else:
        cue.safety_notes.append(
            "ducking is off, so this sits under the commentary at a fixed "
            "level -- check it by ear before trusting it")
    cue.safety_notes.append(
        "a bed longer than its file is tiled, not crossfaded, so a file that "
        "does not loop cleanly will have an audible seam")
    if refused is not None:
        _reject(cue, refused[0], refused[1])
    return cue


# ---------------------------------------------------------------------------
# Safety and budget
# ---------------------------------------------------------------------------

def _speech_spans(
    timeline: StructureTimeline, cut: RoughCutPlan
) -> list[tuple]:
    """Every spoken line, mapped onto the cut. Lines cut out are dropped."""
    from editing.roughcut.select import map_to_sequence

    out: list[tuple] = []
    for segment in timeline.segments:
        for entry in segment.speech_entries:
            if not (entry.text or "").strip():
                continue
            start = map_to_sequence(
                cut.placements, segment.asset_id, entry.start)
            if start is None:
                continue
            end = map_to_sequence(cut.placements, segment.asset_id, entry.end)
            out.append((start, end if end is not None else start + 0.5))
    out.sort()
    return out


def _covers_speech(
    cue: AudioCue, speech: Sequence[tuple], guard: float
) -> Optional[float]:
    """Where a cue would land on a word, or None when it would not.

    ``None`` rather than ``0.0`` for "clear", because a line spoken at the
    very start of the cut is at 0.0 and a falsy sentinel would wave it
    through -- which is the one moment an automated edit most obviously
    announces itself.
    """
    low, high = cue.start - guard, cue.end + guard
    for start, end in speech:
        if high > start and low < end:
            return start
    return None


def _apply_budget(
    cues: list[AudioCue], config: AudioPolishConfig, plan: AudioPolishPlan
) -> None:
    """Thin the surviving cues until they fit the ceilings.

    Only cues that have not already been refused take part: a cue rejected for
    covering speech must not consume budget that a good one could have used.
    """
    live = [cue for cue in cues if not cue.reject_reason]
    minutes = max(plan.cut_duration, 1.0) / 60.0
    allowed = int(config.max_sfx_per_minute * minutes)
    if config.max_sfx_per_minute > 0 and allowed < 1:
        # Same floor the caption budget uses, for the same reason: a rate that
        # rounds down to nothing on a short cut would silently disable the
        # feature rather than limit it.
        allowed = 1
        plan.safety_notes.append(
            f"the cut is {plan.cut_duration:.0f}s, so "
            f"{config.max_sfx_per_minute:.2f} effects a minute rounds down to "
            "none. One was allowed, which reads above the ceiling in the "
            "density figure."
        )

    ranked = sorted(live, key=lambda cue: (-cue.priority, cue.start))
    kept: list[AudioCue] = []
    effects = 0

    for cue in ranked:
        clash = _too_close(cue, kept, config.min_spacing)
        if clash is not None:
            _reject(cue, "too_close_to_another",
                    f"{abs(cue.start - clash.start):.1f}s from the "
                    f"{clash.kind} at {clash.start:.1f}s, and this style asks "
                    f"for {config.min_spacing:.0f}s between two cues")
            continue
        if cue.counts_as_sfx:
            if effects >= allowed:
                _reject(cue, "density_limit",
                        f"the effect budget for this cut is {allowed} "
                        f"({config.max_sfx_per_minute:.1f} a minute over "
                        f"{plan.cut_duration:.0f}s), and stronger moments "
                        "filled it")
                continue
            if len(kept) >= config.max_total:
                _reject(cue, "density_limit",
                        f"the whole-episode ceiling of {config.max_total} "
                        "cue(s) is full")
                continue
            effects += 1
        cue.accepted = True
        kept.append(cue)

    for cue in cues:
        if cue.reject_reason:
            cue.accepted = False


def _too_close(
    cue: AudioCue, kept: Sequence[AudioCue], spacing: float
) -> Optional[AudioCue]:
    """Whether a cue crowds one already kept.

    Beds and silence drops are exempt from spacing against each other and
    against effects: a bed runs *underneath* rather than at a point in time,
    and a silence drop immediately before a hit is the shape the pair is
    supposed to have.
    """
    if cue.kind in ("music_bed", "ambience"):
        return next((other for other in kept
                     if other.kind in ("music_bed", "ambience")), None)
    for other in kept:
        if other.kind in ("music_bed", "ambience"):
            continue
        if cue.kind == "silence_drop" or other.kind == "silence_drop":
            # Only a genuine overlap counts between these two.
            if cue.start < other.end and other.start < cue.end:
                return other
            continue
        if abs(cue.start - other.start) < spacing:
            return other
    return None


# ---------------------------------------------------------------------------
# Assets
# ---------------------------------------------------------------------------

def _resolve_assets(
    cues: Sequence[AudioCue], library, plan: AudioPolishPlan
) -> None:
    """Match accepted cues against the local library.

    A cue that matches nothing stays a placeholder and is marked missing. That
    is the honest outcome and it is also the useful one: the missing list is a
    shopping list.
    """
    from editing.assets.match import best_match, rank_candidates

    if library is None:
        plan.warnings.append(
            "audio polish was asked to use the asset library and none was "
            "available, so every cue stayed a placeholder."
        )
        for cue in cues:
            if cue.accepted and cue.kind in CUE_REQUIREMENT:
                cue.missing_asset = True
                cue.safety_notes.append("no asset library was readable")
        return

    plan.library_root = str(getattr(library, "root", "") or "")
    plan.library_size = len(getattr(library, "items", ()) or ())
    used: dict = {}

    for cue in cues:
        if not cue.accepted:
            continue
        requirement = CUE_REQUIREMENT.get(cue.kind)
        if requirement is None:
            # A silence drop has no file. Not missing -- there is nothing to
            # find, and putting it on a shopping list would be nonsense.
            cue.safety_notes.append(
                "nothing is placed here: the absence of sound is the cue")
            continue

        matches = rank_candidates(
            requirement, library,
            style=plan.style, slot_duration=cue.duration, used=used,
        )
        match = best_match(matches)
        if match is None:
            cue.missing_asset = True
            cue.placeholder_only = True
            cue.safety_notes.append(
                f"nothing in the library satisfies {requirement}")
            continue

        # ``AssetMatch`` carries the id and the filename; the path lives on the
        # library item, and the cue needs it because a person following this
        # plan has to be able to find the file.
        item = library.by_id(match.asset_id)
        cue.asset_id = match.asset_id
        cue.asset_path = str(getattr(item, "path", "") or "")
        cue.asset_filename = match.filename or str(
            getattr(item, "filename", "") or "")
        cue.match_score = float(getattr(match, "score", 0.0) or 0.0)
        cue.placeholder_only = False
        used[cue.asset_id] = used.get(cue.asset_id, 0) + 1
        cue.safety_notes.append(
            "matched on tags, folder and duration. Nothing has listened to "
            "this file and its level has not been measured")


def _finish(
    plan: AudioPolishPlan, cues: Sequence[AudioCue], config: AudioPolishConfig
) -> None:
    plan.cues = list(cues)
    missing = plan.missing
    if missing:
        plan.warnings.append(
            f"{len(missing)} cue(s) have no asset behind them. They are in "
            "the plan as placeholders and on the shopping list."
        )
    if config.uses_library and not plan.library_size:
        plan.warnings.append(
            "the asset library is empty, so every cue is a placeholder. That "
            "list is a useful thing to go shopping with."
        )
    plan.safety_notes.append(
        "No level in this plan has been measured, and nothing here has been "
        "listened to. Check every cue against the commentary by ear."
    )
    plan.safety_notes.append(
        "Nothing in this plan is in the rendered proxy: the proxy assembles "
        "V1 only and carries no added audio."
    )


def _reject(cue: AudioCue, code: str, detail: str) -> None:
    cue.accepted = False
    cue.reject_reason = code
    cue.reject_detail = detail
