"""The feedback collector: what was asked, what was said, and what survives.

Four properties carry the weight, and each is asserted from several angles.

**Nothing is ever lost.** The log is append-only, and that is tested three
ways: appending preserves every earlier line byte for byte, re-rating keeps
both versions, and starting a session over one that holds feedback is refused.
This is the only artifact in the whole system that cannot be regenerated by
re-running a pass, so losing a line of it is unrecoverable in a way nothing
else here is.

**Feedback stays attached to evidence.** A rating resolves to the record it
was about, keeps the artifact path and the source IDs, and an ID that matches
nothing produces an error naming every collection that was searched -- because
the usual cause is a pass that never ran, not a typo.

**Uncertainty survives.** ``unsure`` is a rating, never coerced away, and it is
structurally incapable of becoming training data. A preference built on two
ratings cannot claim the confidence of one built on six, and disagreement is
counted rather than filtered out.

**Nothing is trained, and nothing is claimed.** No pass reads a preference
signal; ``safe_to_apply_automatically`` describes evidence rather than granting
permission; and every report carries ``NOT_MEASURED`` verbatim.

Nothing here needs FFmpeg, a GPU, a model server, Premiere or real footage.
"""
from __future__ import annotations

import json

import pytest

from editing.assets.schema import AssetMatch, AssetPlacement, AssetPlacementPlan
from editing.critic.schema import (
    CriticFinding, CriticReport, RevisionRecommendation, RevisionSet,
)
from editing.episode.schema import (
    ClimaxCandidate, EndingCandidate, EpisodeBeat, EpisodeCallback,
    EpisodeEvidence, EpisodeMemory, EpisodeOpenLoop, EpisodeRetentionPlan,
    EpisodeRiskZone, EpisodeSetup, HookCandidate, RetentionSuggestion,
)
from editing.errors import EditingError
from editing.feedback import collect as collect_module
from editing.feedback import export as export_module
from editing.feedback import queue as queue_module
from editing.feedback import report as feedback_report
from editing.feedback import signals as signals_module
from editing.feedback import store as store_module
from editing.feedback import targets as targets_module
from editing.feedback import training as training_module
from editing.feedback.schema import (
    DEFAULT_REASON_FOR_RATING, FeedbackCorrection, FeedbackItem,
    FeedbackRating, FeedbackSession, FeedbackTarget, NOT_MEASURED,
    POLARITY_FOR_RATING, PREFERENCE_DIMENSIONS, PREFERENCE_STATEMENTS,
    RATINGS, REASON_CATEGORIES, ReviewPrompt, ReviewQueue, TARGET_TYPES,
    TASK_FOR_TARGET, TASK_TYPES, TrainingSignal, action_from_text,
    build_correction, preference_cap, reasons_from,
)
from editing.recommend.schema import (
    EditRecommendation, Evidence, RecommendationSet,
)
from editing.roughcut.schema import ClipPlacement, RoughCutPlan, Unconverted
from editing.style.schema import LayeredEditPlan, LayerItem

SEQUENCE = "Nova Rough Cut"


# ---------------------------------------------------------------------------
# Builders -- one full set of artifacts, so the queue has every source
# ---------------------------------------------------------------------------

def a_rough_cut(clips: int = 4) -> RoughCutPlan:
    return RoughCutPlan(
        sequence_name=SEQUENCE,
        placements=[
            ClipPlacement(
                placement_id=f"p_{index}", asset_id="a1",
                source_file="/footage/ep12.mp4",
                source_in=index * 40.0, source_out=index * 40.0 + 30.0,
                sequence_start=index * 30.0, index=index,
                segment_ids=[f"s_{index}"], keep_reason="high interest",
                recommendation_ids=[f"rec_{index}"] if index % 2 else [],
                protected=(index == 1),
            )
            for index in range(clips)
        ],
        unconverted=[Unconverted(
            recommendation_id="rec_dropped", category="punch_in",
            start=12.0, end=14.0, reason="no evidence to act on",
        )],
        on_scratch=True,
    )


def some_recommendations() -> RecommendationSet:
    return RecommendationSet(recommendations=[
        EditRecommendation(
            recommendation_id="rec_1", asset_id="a1",
            source_file="/footage/ep12.mp4", start=10.0, end=14.0,
            category="punch_in", priority=0.82, reason="the creeper moment",
            evidence=Evidence(visual_event_ids=["e1"],
                              transcript_quotes=["oh god"]),
            status="accepted",
        ),
        EditRecommendation(
            recommendation_id="rec_2", asset_id="a1",
            source_file="/footage/ep12.mp4", start=40.0, end=44.0,
            category="text_overlay", priority=0.40, reason="worth a caption",
            status="rejected", status_reason="too many overlays already",
        ),
        EditRecommendation(
            recommendation_id="rec_3", asset_id="a1",
            source_file="/footage/ep12.mp4", start=60.0, end=72.0,
            category="hold", priority=0.60, reason="strong raw",
            status="hold",
        ),
    ])


def a_critique() -> CriticReport:
    return CriticReport(
        sequence_name=SEQUENCE,
        findings=[
            CriticFinding(
                finding_id="f_1", frame_id="fr_1", issue="jump_cut",
                severity="high", confidence=0.8, evidence="the cut jumps",
                suggested_fix="add_transition", sequence_time=30.0,
                placement_id="p_1",
            ),
            CriticFinding(
                finding_id="f_2", frame_id="fr_2", issue="unclear_action",
                severity="low", confidence=0.3, evidence="hard to read",
                sequence_time=95.0,
            ),
        ],
        frames_examined=12,
    )


def some_revisions() -> RevisionSet:
    return RevisionSet(sequence_name=SEQUENCE, revisions=[
        RevisionRecommendation(
            revision_id="rev_1", finding_id="f_1", placement_id="p_1",
            start=30.0, end=32.0, issue="jump_cut", severity="high",
            confidence=0.78, suggested_fix="add_transition",
            fix_detail="a short dissolve", status="accepted",
        ),
        RevisionRecommendation(
            revision_id="rev_2", finding_id="f_2", start=95.0, end=96.0,
            issue="unclear_action", severity="low", confidence=0.35,
            suggested_fix="add_marker", status="rejected",
            status_reason="the critic was not sure enough",
        ),
    ])


def some_layers() -> LayeredEditPlan:
    return LayeredEditPlan(sequence_name=SEQUENCE, style="fast_funny", items=[
        LayerItem(item_id="li_danger", layer="caption", kind="danger_text",
                  start=12.0, end=15.0, reason="a creeper is right there",
                  priority=0.84, status="planned", payload={"text": "RUN"},
                  placement_id="p_0"),
        LayerItem(item_id="li_react", layer="caption",
                  kind="reaction_caption", start=41.0, end=44.0,
                  reason="a laugh", priority=0.35, status="deferred",
                  status_reason="caption ceiling reached",
                  payload={"text": "no way"}),
        LayerItem(item_id="li_punch", layer="emphasis", kind="punch_in",
                  start=70.0, end=72.0, reason="impact", priority=0.90,
                  status="planned", risks=["hides_gameplay"]),
        LayerItem(item_id="li_mark", layer="marker", kind="structure_marker",
                  start=90.0, end=90.5, reason="section boundary",
                  priority=0.30, status="planned"),
    ])


def an_asset_plan() -> AssetPlacementPlan:
    return AssetPlacementPlan(sequence_name=SEQUENCE, style="fast_funny",
                              placements=[
        AssetPlacement(
            placement_id="ap_1", item_id="li_danger", kind="impact_sfx",
            layer="audio", start=12.0, end=13.0,
            library_asset_id="lib_1", asset_path="/lib/sfx/boom.wav",
            asset_filename="boom.wav", track="A2", status="placed",
            reason="matched on tags: danger, impact",
            candidates=[AssetMatch(asset_id="lib_1", score=0.81)],
        ),
        AssetPlacement(
            placement_id="ap_2", item_id="li_punch", kind="whoosh",
            layer="audio", start=70.0, end=70.5, status="missing",
            reason="the library has no whoosh at all",
            risks=["no_asset"],
        ),
    ])


def an_episode_memory() -> EpisodeMemory:
    evidence = EpisodeEvidence(segment_ids=["s_0"], quotes=["let us go"],
                               visual_event_ids=["e1"])
    return EpisodeMemory(
        episode_id="ep_1", name="structure", sequence_name=SEQUENCE,
        timebase="roughcut", duration=120.0,
        beats=[
            EpisodeBeat(item_id="beat_1", start=0.0, end=20.0, kind="setup",
                        confidence=0.62, why="establishing", evidence=evidence),
            EpisodeBeat(item_id="beat_2", start=20.0, end=60.0, kind="grind",
                        confidence=0.40, why="mining for a while",
                        evidence=evidence),
            EpisodeBeat(item_id="beat_3", start=60.0, end=90.0,
                        kind="climax", confidence=0.70, why="the big fight",
                        evidence=evidence),
            EpisodeBeat(item_id="beat_4", start=90.0, end=120.0,
                        kind="unknown", confidence=0.20,
                        why="nothing could be read", evidence=evidence),
        ],
        setups=[EpisodeSetup(item_id="set_1", start=5.0, end=9.0,
                             text="we need diamonds", topic="diamonds",
                             payoff_id="pay_1", confidence=0.55,
                             evidence=evidence)],
        open_loops=[
            EpisodeOpenLoop(item_id="loop_1", start=5.0, end=9.0,
                            question="will they find diamonds?",
                            topic="diamonds", status="open",
                            confidence=0.48, evidence=evidence),
        ],
        callbacks=[EpisodeCallback(item_id="cb_1", start=100.0, end=103.0,
                                   label="the diamond joke", kind="joke",
                                   refers_to_time=8.0, confidence=0.52,
                                   suggested_text="remember the diamonds",
                                   evidence=evidence)],
    )


def a_retention_plan() -> EpisodeRetentionPlan:
    return EpisodeRetentionPlan(
        episode_id="ep_1", name="structure", sequence_name=SEQUENCE,
        timebase="roughcut", duration=120.0,
        risks=[
            EpisodeRiskZone(item_id="risk_1", start=20.0, end=60.0,
                            risk="boring_repetition", severity="high",
                            score=0.8, confidence=0.62,
                            why="forty seconds of the same action",
                            suggested_fix="shorten_boring"),
            EpisodeRiskZone(item_id="risk_2", start=95.0, end=105.0,
                            risk="dead_air", severity="medium", score=0.5,
                            confidence=0.66, why="measured silence",
                            fix_is_safe_automatically=True),
        ],
        hooks=[
            HookCandidate(item_id="hook_1", start=62.0, end=66.0,
                          hook_type="danger", score=0.75, confidence=0.66,
                          suggested_text="this went badly",
                          text_source="transcript_quote",
                          why="stakes a stranger could read"),
        ],
        climax=ClimaxCandidate(item_id="clx_1", start=60.0, end=90.0,
                               confidence=0.7, why="the biggest moment"),
        ending=EndingCandidate(item_id="end_1", start=110.0, end=120.0,
                               confidence=0.5, why="it signs off"),
        suggestions=[
            RetentionSuggestion(item_id="sug_1", start=20.0, end=60.0,
                                type="shorten_boring", confidence=0.60,
                                reason="the middle sags",
                                downstream="roughcut"),
            RetentionSuggestion(item_id="sug_2", start=100.0, end=103.0,
                                type="add_callback_caption", confidence=0.58,
                                reason="a callback worth naming",
                                downstream="style", auto_safe=True),
        ],
    )


@pytest.fixture
def artifacts() -> targets_module.Artifacts:
    """One complete set, so every queue generator has something to read."""
    return targets_module.Artifacts(
        name="structure", style="fast_funny", run_id="run_x",
        artifact_root="/tmp/artifacts",
        recommendations=some_recommendations(),
        roughcut=a_rough_cut(),
        critique=a_critique(),
        revisions=some_revisions(),
        layers=some_layers(),
        asset_plan=an_asset_plan(),
        memory=an_episode_memory(),
        retention=a_retention_plan(),
    )


@pytest.fixture
def session(config, artifacts) -> FeedbackSession:
    return collect_module.start_session(
        config, artifacts, run_id="run_x", title="a review")


def rate(config, session, artifacts, ident, rating, **kwargs):
    return collect_module.rate(
        config, session, artifacts, ident, rating, **kwargs)


# ---------------------------------------------------------------------------
# Part 1 -- the schema
# ---------------------------------------------------------------------------

def test_every_rating_has_a_polarity_and_a_reason_category():
    """The two lookups every consumer depends on must cover the vocabulary.

    A rating missing from either table would silently become "neutral" and
    "preference", which is a wrong label rather than a missing one.
    """
    for rating in RATINGS:
        assert rating in POLARITY_FOR_RATING, rating
        assert rating in DEFAULT_REASON_FOR_RATING, rating
        assert DEFAULT_REASON_FOR_RATING[rating] in REASON_CATEGORIES


def test_the_prompt_vocabulary_is_covered():
    assert len(set(RATINGS)) == len(RATINGS), "a rating is listed twice"
    for expected in ("good", "bad", "okay", "unsure", "keep", "cut",
                     "shorten", "extend", "move_earlier", "move_later",
                     "too_much", "too_little", "wrong_moment", "wrong_style",
                     "funny", "boring", "confusing", "hype", "useful_context",
                     "useless_context", "bad_caption", "good_caption",
                     "bad_music_sfx", "good_music_sfx", "bad_hook",
                     "good_hook", "bad_pacing", "strong_payoff",
                     "weak_payoff", "good_callback", "forced_callback",
                     "strong_retention", "weak_retention"):
        assert expected in RATINGS, expected
    for category in ("pacing", "story", "clarity", "retention", "comedy",
                     "emotion", "visual", "audio", "caption", "timing",
                     "style", "safety", "technical", "preference"):
        assert category in REASON_CATEGORIES, category


def test_every_target_type_maps_to_a_training_task():
    for target_type in TARGET_TYPES:
        assert target_type in TASK_FOR_TARGET, target_type
        assert TASK_FOR_TARGET[target_type] in TASK_TYPES


def test_a_feedback_item_round_trips_through_json(session):
    item = FeedbackItem(
        session_id=session.session_id,
        target=FeedbackTarget(target_type="layer_item", target_id="li_danger",
                              start=12.0, end=15.0, label="a caption",
                              resolved=True, checked=True),
        rating=FeedbackRating(rating="too_much", strength=0.8),
        note="one too many",
        correction=build_correction("cut this shorter", seconds=1.5),
        confidence=0.9,
    ).settle()

    restored = FeedbackItem.from_dict(
        json.loads(json.dumps(item.to_dict()))
    )
    assert restored.feedback_id == item.feedback_id
    assert restored.rating.rating == "too_much"
    assert restored.polarity == "corrective"
    assert restored.correction is not None
    assert restored.correction.action == "shorten"
    assert restored.correction.seconds == 1.5
    assert restored.target.target_id == "li_danger"


def test_an_unknown_rating_is_refused_rather_than_coerced(
    config, session, artifacts
):
    """A typo must not enter the data as a real opinion.

    The whole vocabulary exists so ratings can be counted; coercing 'meh' to
    'okay' would put a neutral judgement in the log that nobody gave.
    """
    with pytest.raises(EditingError) as error:
        rate(config, session, artifacts, "li_danger", "meh")
    assert "not a rating" in str(error.value)
    assert "good" in error.value.hint


def test_reason_words_from_the_rating_vocabulary_are_kept_not_dropped():
    """``--reason boring`` is what people type, and it means something."""
    reasons = reasons_from(["boring"])
    assert [r.category for r in reasons] == ["pacing"]
    assert "boring" in reasons[0].detail

    # An unknown word is filed rather than discarded.
    unknown = reasons_from(["the music swells oddly"])
    assert unknown[0].category == "preference"
    assert "music swells" in unknown[0].detail


def test_a_correction_action_is_read_longest_phrase_first():
    """"cut this shorter" is a shorten, not a cut.

    Same rule as Session 8's cue families: a short phrase inside a longer one
    must not be able to claim it.
    """
    assert action_from_text("cut this shorter") == "shorten"
    assert action_from_text("cut this") == "cut"
    assert action_from_text("move it later") == "move_later"
    assert action_from_text("") == "none"


def test_a_directional_correction_with_no_number_is_not_specific():
    vague = build_correction("make it shorter")
    assert vague is not None and vague.action == "shorten"
    assert not vague.is_specific, "no idea how much shorter"

    exact = build_correction("make it shorter", seconds=-2.0)
    assert exact is not None and exact.is_specific

    # A non-measurable correction is specific enough as text alone.
    swap = build_correction("different music please")
    assert swap is not None and swap.is_specific


def test_an_unsure_rating_can_never_be_training_data(session):
    item = FeedbackItem(
        session_id=session.session_id,
        target=FeedbackTarget(target_type="whole_edit", resolved=True),
        rating=FeedbackRating(rating="unsure"),
        usable_for_training=True,          # asked for, and overruled
    ).settle()
    assert item.usable_for_training is False
    assert "unsure" in item.training_note


def test_an_untraceable_target_cannot_be_training_data(session):
    item = FeedbackItem(
        session_id=session.session_id,
        target=FeedbackTarget(target_type="layer_item", target_id="li_gone",
                              checked=True, resolved=False),
        rating=FeedbackRating(rating="bad"),
    ).settle()
    assert item.usable_for_training is False
    assert item.needs_follow_up is True


def test_a_directional_rating_with_no_correction_asks_for_one(session):
    item = FeedbackItem(
        session_id=session.session_id,
        target=FeedbackTarget(target_type="timeline_range", start=1.0,
                              end=5.0, resolved=True),
        rating=FeedbackRating(rating="shorten"),
    ).settle()
    assert item.needs_follow_up is True
    assert "how far" in item.follow_up_note


# ---------------------------------------------------------------------------
# Part 2 -- sessions and the append-only log
# ---------------------------------------------------------------------------

def test_starting_a_session_records_what_there_was_to_review(config, artifacts):
    session = collect_module.start_session(config, artifacts, run_id="run_x")
    directory = store_module.session_dir(config, session.session_id)

    assert (directory / "session.json").exists()
    assert (directory / "feedback.jsonl").exists()
    assert (directory / "exports").is_dir()
    assert session.sequence_name == SEQUENCE
    assert session.timebase == "roughcut"
    assert session.sources["roughcut"] is True
    assert session.sources["timeline"] is False


def test_a_session_over_a_partial_pipeline_says_what_it_could_not_see(config):
    thin = targets_module.Artifacts(roughcut=a_rough_cut())
    session = collect_module.start_session(config, thin)
    joined = " ".join(session.warnings)
    assert "critique" in joined and "asset_plan" in joined
    assert "absent" in joined


def test_a_session_is_never_started_over_one_holding_feedback(
    config, session, artifacts
):
    """The one artifact here that cannot be regenerated by re-running a pass."""
    rate(config, session, artifacts, "li_danger", "good")
    with pytest.raises(EditingError) as error:
        collect_module.start_session(
            config, artifacts, session_id=session.session_id)
    assert "already exists" in str(error.value)
    assert "never overwritten" in error.value.hint

    # ...and not even with --force, once there is something in it.
    with pytest.raises(EditingError):
        collect_module.start_session(
            config, artifacts, session_id=session.session_id, force=True)


def test_two_sessions_over_the_same_run_stay_separate(config, artifacts):
    first = collect_module.start_session(
        config, artifacts, run_id="run_x", session_id="s-one")
    second = collect_module.start_session(
        config, artifacts, run_id="run_x", session_id="s-two")
    rate(config, first, artifacts, "li_danger", "good")

    assert store_module.count(config, "s-one") == 1
    assert store_module.count(config, "s-two") == 0
    assert {s.session_id for s in store_module.list_sessions(config)} >= {
        "s-one", "s-two"}


def test_appending_never_rewrites_an_earlier_line(config, session, artifacts):
    """The load-bearing guarantee of the whole layer, asserted on bytes."""
    rate(config, session, artifacts, "li_danger", "good")
    path = store_module.log_path(config, session.session_id)
    after_one = path.read_bytes()

    rate(config, session, artifacts, "li_punch", "bad")
    rate(config, session, artifacts, "p_0", "keep")
    after_three = path.read_bytes()

    assert after_three.startswith(after_one), (
        "an earlier line was rewritten; the log must only ever grow")
    assert len(after_three.splitlines()) == 3


def test_re_rating_supersedes_without_deleting(config, session, artifacts):
    first = rate(config, session, artifacts, "li_danger", "bad",
                 note="too much")
    second = rate(config, session, artifacts, "li_danger", "good_caption",
                  note="changed my mind")

    history = store_module.read_all(config, session.session_id)
    current = store_module.read_current(config, session.session_id)

    assert len(history) == 2, "the original opinion is still in the file"
    assert len(current) == 1, "only the later one stands"
    assert current[0].feedback_id == second.feedback_id
    assert second.supersedes == first.feedback_id
    assert [item.rating.rating for item in
            store_module.history_of(history, first.target.key())] == [
        "bad", "good_caption"]


def test_changing_your_mind_does_not_move_the_item_down_the_list(
    config, session, artifacts
):
    """A reviewer reading top to bottom should not have items jump around.

    ``read_current`` is a view over the log, so the naive implementation orders
    by last write -- re-rating the first item sends it to the bottom, which is
    the opposite of what someone working through a list wants.
    """
    rate(config, session, artifacts, "li_danger", "bad")
    rate(config, session, artifacts, "li_punch", "good")
    rate(config, session, artifacts, "p_0", "keep")
    rate(config, session, artifacts, "li_danger", "good_caption")

    current = store_module.read_current(config, session.session_id)
    assert [item.target.target_id for item in current] == [
        "li_danger", "li_punch", "p_0"]
    assert current[0].rating.rating == "good_caption", "and it is the new one"


def test_a_corrupt_line_costs_one_line_and_not_the_review(
    config, session, artifacts
):
    rate(config, session, artifacts, "li_danger", "good")
    path = store_module.log_path(config, session.session_id)
    with open(path, "a", encoding="utf-8") as handle:
        handle.write("{not json at all\n")
    rate(config, session, artifacts, "li_punch", "bad")

    assert len(store_module.read_all(config, session.session_id)) == 2
    problems = store_module.read_problems(config, session.session_id)
    assert len(problems) == 1 and "line 2" in problems[0]


def test_the_latest_session_is_the_one_commands_default_to(config, artifacts):
    collect_module.start_session(
        config, artifacts, session_id="20260101T000000-fb-aaa")
    newest = collect_module.start_session(
        config, artifacts, session_id="20260202T000000-fb-bbb")
    resolved = store_module.resolve_session(config)
    assert resolved.session_id == newest.session_id


def test_asking_for_a_session_that_does_not_exist_says_how_to_start_one(config):
    with pytest.raises(EditingError) as error:
        store_module.resolve_session(config)
    assert "feedback start" in error.value.hint


# ---------------------------------------------------------------------------
# Part 3 -- the review queue
# ---------------------------------------------------------------------------

def test_the_queue_draws_on_every_pass_that_ran(artifacts):
    queue = queue_module.build(artifacts, limit=60)
    sources = {prompt.source for prompt in queue.prompts}
    assert {"roughcut", "recommend", "critic", "style", "assets", "episode",
            "retention", "edit"} <= sources


def test_the_queue_prioritises_uncertain_and_high_impact_decisions(artifacts):
    queue = queue_module.build(artifacts, limit=10)
    top = queue.prompts[:5]
    interesting = [
        prompt for prompt in top
        if prompt.has_flag("uncertain") or prompt.has_flag("high_impact")
        or prompt.has_flag("structural")
    ]
    assert len(interesting) >= 4, [p.line() for p in top]

    # ...and the flags genuinely raise priority rather than being decoration.
    flagged = [p for p in queue.prompts if p.has_flag("structural")]
    plain = [p for p in queue.prompts
             if not p.flags or p.flags == ["positive_sample"]]
    if flagged and plain:
        assert max(p.priority for p in flagged) > min(
            p.priority for p in plain)


def test_the_queue_includes_retention_risks_and_hook_candidates(artifacts):
    queue = queue_module.build(artifacts, limit=25)
    assert queue.flagged("retention_risk"), "a risk zone must reach the queue"
    assert queue.flagged("structural"), "hooks/peak/ending must reach it"

    questions = " ".join(prompt.question for prompt in queue.prompts)
    assert "open the video" in questions
    assert "boring_repetition" in questions


def test_the_queue_includes_setup_payoff_pairs_and_callbacks(artifacts):
    queue = queue_module.build(artifacts, limit=40)
    pairs = queue.flagged("setup_payoff")
    assert pairs, "a setup with a payoff must be reviewable as a pair"
    kinds = {prompt.target.target_type for prompt in pairs}
    assert "callback" in kinds or "open_loop" in kinds


def test_the_queue_keeps_a_few_decisions_that_look_right(artifacts):
    """A review made only of problems teaches what to avoid and nothing else."""
    queue = queue_module.build(artifacts, limit=20)
    positive = queue.flagged("positive_sample")
    assert positive, "no sample of good decisions was included"
    assert len(positive) <= max(1, int(20 * queue_module.POSITIVE_RATIO)) + 1


def test_no_positive_leaves_them_out(artifacts):
    queue = queue_module.build(artifacts, limit=20, include_positive=False)
    assert not queue.flagged("positive_sample")


def test_the_queue_dedupes_two_prompts_about_one_record(artifacts):
    queue = queue_module.build(artifacts, limit=60)
    keys = [prompt.target.key() for prompt in queue.prompts]
    assert len(keys) == len(set(keys)), "one record, one question"


def test_near_identical_prompts_at_one_moment_collapse():
    """Three captions in five seconds is one thing to look at, not three."""
    def caption(index: int, start: float) -> ReviewPrompt:
        return ReviewPrompt(
            prompt_id=f"q_{index}", source="style", category="caption",
            priority=0.4 + index * 0.01,
            target=FeedbackTarget(target_type="layer_item",
                                  target_id=f"li_{index}",
                                  start=start, end=start + 1.0),
        )

    folded = queue_module.collapse_nearby(
        [caption(0, 10.0), caption(1, 11.0), caption(2, 13.0),
         caption(3, 60.0)]
    )
    assert len(folded) == 2, [p.prompt_id for p in folded]
    kept = max(folded, key=lambda p: p.duplicates)
    assert kept.duplicates == 2

    # A different kind of thing at the same moment is a busy moment, not a
    # duplicate, and is left alone.
    asset = ReviewPrompt(
        prompt_id="q_a", source="assets", category="audio", priority=0.5,
        target=FeedbackTarget(target_type="asset_placement",
                              target_id="ap_1", start=10.5, end=11.0),
    )
    mixed = queue_module.collapse_nearby([caption(0, 10.0), asset])
    assert len(mixed) == 2


def test_prompts_near_each_other_share_a_group(artifacts):
    queue = queue_module.build(artifacts, limit=60)
    for group in queue.groups():
        if len(group) < 2:
            continue
        spread = max(p.start for p in group) - min(p.start for p in group)
        # The walk starts a new group when the gap from the group's anchor
        # exceeds the window, so a group can span at most one window's worth
        # of steps beyond it.
        assert spread <= queue_module.GROUP_WINDOW * len(group)


def test_grouping_does_not_split_on_a_bucket_boundary():
    """Two prompts a second apart belong together whatever the clock says."""
    prompts = [
        ReviewPrompt(prompt_id="q_a", target=FeedbackTarget(
            target_type="timeline_range", start=14.9, end=15.0)),
        ReviewPrompt(prompt_id="q_b", target=FeedbackTarget(
            target_type="timeline_range", start=15.1, end=15.2)),
    ]
    queue_module.assign_groups(prompts)
    assert prompts[0].group_id == prompts[1].group_id


def test_the_limit_is_honoured_and_what_it_dropped_is_reported(artifacts):
    queue = queue_module.build(artifacts, limit=6)
    assert len(queue.prompts) == 6
    assert queue.candidates > 6
    assert queue.stats()["dropped_by_limit"] == queue.candidates - 6
    assert any("did not fit" in warning for warning in queue.warnings)


def test_a_small_limit_still_covers_more_than_one_pass(artifacts):
    """The reserved slots exist so the style layer cannot flood a short queue."""
    queue = queue_module.build(artifacts, limit=8)
    assert len({prompt.source for prompt in queue.prompts}) >= 3


def test_the_queue_can_be_filtered_by_category_and_source(artifacts):
    captions = queue_module.build(artifacts, limit=40, categories=["caption"])
    assert captions.prompts
    assert {p.category for p in captions.prompts} == {"caption"}

    audio = queue_module.build(artifacts, limit=40, sources=["assets"])
    assert audio.prompts
    assert {p.source for p in audio.prompts} == {"assets"}


def test_a_queue_says_which_passes_it_could_not_ask_about():
    thin = targets_module.Artifacts(roughcut=a_rough_cut())
    queue = queue_module.build(thin, limit=20)
    joined = " ".join(queue.warnings)
    assert "critique" in joined and "retention_plan" in joined
    assert "absent rather than approved" in joined


def test_an_empty_queue_says_so_rather_than_implying_perfection():
    queue = queue_module.build(targets_module.Artifacts(), limit=20)
    assert len(queue.prompts) == 1, "only the whole-edit question survives"
    assert any("no artifacts were found" in warning
               for warning in queue.warnings)


def test_every_prompt_says_what_the_system_decided(artifacts):
    """Feedback given without this is about the video, not about a decision."""
    queue = queue_module.build(artifacts, limit=60)
    for prompt in queue.prompts:
        assert prompt.question, prompt.prompt_id
        assert prompt.why_asked, prompt.prompt_id
        assert prompt.system_decision, prompt.prompt_id
        assert prompt.suggested_ratings, prompt.prompt_id
        for rating in prompt.suggested_ratings:
            assert rating in RATINGS, (prompt.prompt_id, rating)


def test_a_broken_artifact_costs_its_own_prompts_and_not_the_queue(artifacts):
    """One malformed record must not lose the other forty questions."""
    class Exploding:
        @property
        def placements(self):
            raise RuntimeError("this artifact is broken")

    artifacts.asset_plan = Exploding()
    queue = queue_module.build(artifacts, limit=40)
    assert queue.prompts
    assert not queue.of_source("assets")
    assert any("_from_assets" in warning for warning in queue.warnings)


def test_the_queue_round_trips_through_json(artifacts):
    queue = queue_module.build(artifacts, limit=12)
    restored = ReviewQueue.from_dict(json.loads(json.dumps(queue.to_dict())))
    assert len(restored.prompts) == len(queue.prompts)
    assert restored.prompts[0].prompt_id == queue.prompts[0].prompt_id
    assert restored.prompts[0].flags == queue.prompts[0].flags
    assert restored.timebase == "roughcut"


def test_the_estimate_needs_no_session(artifacts):
    estimate = queue_module.estimate(artifacts)
    assert estimate["worth_reviewing"] > 0
    assert estimate["suggested_limit"] <= queue_module.DEFAULT_LIMIT
    assert estimate["basis"] == NOT_MEASURED


# ---------------------------------------------------------------------------
# Part 4 -- recording feedback
# ---------------------------------------------------------------------------

def test_rating_a_queue_prompt_keeps_the_question_it_answered(
    config, session, artifacts
):
    queue = queue_module.build(
        artifacts, session_id=session.session_id, limit=20)
    store_module.write_queue(config, session.session_id, queue)
    prompt = queue.prompts[0]

    item = rate(config, session, artifacts, prompt.prompt_id, "good",
                reasons=["pacing"], note="This cut feels clean")
    assert item.prompt_id == prompt.prompt_id
    assert item.target.key() == prompt.target.key()
    assert item.note == "This cut feels clean"
    assert item.usable_for_training is True


def test_rating_a_record_id_directly_resolves_it(config, session, artifacts):
    item = rate(config, session, artifacts, "li_danger", "too_much",
                reasons=["caption"])
    assert item.target.target_type == "layer_item"
    assert item.target.resolved is True
    assert item.target.artifact == "layers/structure.json"
    assert item.target.start == 12.0 and item.target.end == 15.0
    assert "danger_text" in item.target.label


def test_a_range_and_the_whole_edit_are_both_ratable(
    config, session, artifacts
):
    span = rate(config, session, artifacts, "120-155", "boring",
                reasons=["pacing"])
    assert span.target.target_type == "timeline_range"
    assert (span.target.start, span.target.end) == (120.0, 155.0)
    assert span.target.is_traceable

    whole = rate(config, session, artifacts, "whole", "good")
    assert whole.target.target_type == "whole_edit"
    assert whole.target.end == artifacts.duration


def test_an_id_that_matches_nothing_says_where_it_looked(
    config, session, artifacts
):
    """The usual cause is a pass that never ran, not a typo."""
    with pytest.raises(EditingError) as error:
        rate(config, session, artifacts, "li_imaginary", "good")
    message = str(error.value)
    assert "li_imaginary" in message
    assert "layer_item" in error.value.hint
    assert error.value.detail["counts"]["layer_item"] == 4
    assert "feedback rate --range" in error.value.hint


def test_an_unknown_id_can_be_kept_deliberately(config, session, artifacts):
    item = collect_module.rate(
        config, session, artifacts, "li_imaginary", "bad", strict=False)
    assert item.target.resolved is False
    assert item.target.checked is True
    assert item.needs_follow_up is True
    assert item.usable_for_training is False
    assert store_module.count(config, session.session_id) == 1


def test_a_note_keeps_the_rating_that_already_stands(
    config, session, artifacts
):
    rate(config, session, artifacts, "li_danger", "too_much")
    noted = collect_module.add_note(
        config, session, artifacts, "li_danger",
        "it sits over the hotbar")

    assert noted.rating.rating == "too_much", "a note is not a verdict"
    assert "hotbar" in noted.note
    assert noted.supersedes


def test_a_note_with_no_rating_is_not_a_neutral_judgement(
    config, session, artifacts
):
    """Recording ``okay`` as a *label* would be a judgement nobody gave."""
    noted = collect_module.add_note(
        config, session, artifacts, "li_punch", "the zoom is very fast")
    assert noted.usable_for_training is False
    assert "note rather than a rating" in noted.training_note


def test_a_correction_answers_the_follow_up_a_rating_left_open(
    config, session, artifacts
):
    asked = rate(config, session, artifacts, "p_0", "shorten")
    assert asked.needs_follow_up is True

    fixed = collect_module.add_correction(
        config, session, artifacts, "p_0", "cut this shorter", seconds=-4.0)
    assert fixed.rating.rating == "shorten", "the rating is kept"
    assert fixed.correction is not None
    assert fixed.correction.action == "shorten"
    assert fixed.needs_follow_up is False
    assert fixed.supersedes == asked.feedback_id


def test_a_correction_with_no_rating_infers_one(config, session, artifacts):
    item = collect_module.add_correction(
        config, session, artifacts, "li_punch", "move it later", seconds=2.0)
    assert item.rating.rating == "move_later"
    assert item.correction is not None and item.correction.seconds == 2.0


def test_an_empty_note_or_correction_is_refused(config, session, artifacts):
    with pytest.raises(EditingError):
        collect_module.add_note(config, session, artifacts, "li_danger", "  ")
    with pytest.raises(EditingError):
        collect_module.add_correction(
            config, session, artifacts, "li_danger", "")


def test_the_queue_shows_what_has_already_been_answered(
    config, session, artifacts
):
    queue = queue_module.build(
        artifacts, session_id=session.session_id, limit=20)
    store_module.write_queue(config, session.session_id, queue)
    rate(config, session, artifacts, queue.prompts[0].prompt_id, "good")

    collect_module.mark_answered(
        queue, store_module.read_current(config, session.session_id))
    assert queue.prompts[0].answered is True
    assert queue.stats()["answered"] == 1


def test_answering_a_record_directly_ticks_off_its_queue_entry(
    config, session, artifacts
):
    queue = queue_module.build(
        artifacts, session_id=session.session_id, limit=40)
    store_module.write_queue(config, session.session_id, queue)
    rate(config, session, artifacts, "li_danger", "good_caption")

    collect_module.mark_answered(
        queue, store_module.read_current(config, session.session_id))
    caption = queue.prompt(
        next(p.prompt_id for p in queue.prompts
             if p.target.target_id == "li_danger")
    )
    assert caption.answered is True


def test_a_prompt_stays_findable_after_the_queue_is_regenerated(
    config, session, artifacts
):
    """A rating references a prompt ID, so that question must stay readable."""
    first = queue_module.build(
        artifacts, session_id=session.session_id, limit=8)
    store_module.write_queue(config, session.session_id, first)
    old_id = first.prompts[0].prompt_id

    second = queue_module.build(
        artifacts, session_id=session.session_id, limit=8,
        categories=["audio"])
    store_module.write_queue(config, session.session_id, second)

    found = store_module.find_prompt(config, session.session_id, old_id)
    assert found is not None and found.prompt_id == old_id


def test_counts_are_derived_from_the_log_not_incremented(
    config, session, artifacts
):
    rate(config, session, artifacts, "li_danger", "bad")
    rate(config, session, artifacts, "li_danger", "good_caption")
    rate(config, session, artifacts, "p_0", "keep")
    refreshed = collect_module.refresh_counts(config, session)

    assert refreshed.counts["items"] == 2
    assert refreshed.counts["history"] == 3
    assert refreshed.counts["superseded"] == 1


# ---------------------------------------------------------------------------
# Part 5 -- preference signals
# ---------------------------------------------------------------------------

def test_every_preference_dimension_can_be_put_into_words():
    """A dimension with no sentence would render as a placeholder in a report."""
    covered = {dimension for dimension, _direction in PREFERENCE_STATEMENTS}
    for rule in signals_module.RULES:
        assert rule.dimension in PREFERENCE_DIMENSIONS, rule.dimension
        assert (rule.dimension, rule.direction) in PREFERENCE_STATEMENTS, (
            rule.dimension, rule.direction)
    assert covered <= set(PREFERENCE_DIMENSIONS)


def test_repeated_caption_complaints_become_one_preference(
    config, session, artifacts
):
    for target in ("li_danger", "li_react", "li_punch"):
        rate(config, session, artifacts, target, "too_much",
             reasons=["caption"], confidence=0.9)

    found = signals_module.extract(
        store_module.read_current(config, session.session_id),
        style="fast_funny")
    density = next(s for s in found if s.dimension == "caption_density")
    assert density.direction == "less"
    assert density.evidence_count == 3
    assert density.statement == "dislikes having many captions on screen"
    assert density.is_style_specific and density.style == "fast_funny"
    assert len(density.source_feedback_ids) == 3


def test_a_preference_stated_once_stays_tentative(config, session, artifacts):
    rate(config, session, artifacts, "li_danger", "too_much",
         reasons=["caption"], confidence=1.0)
    found = signals_module.extract(
        store_module.read_current(config, session.session_id))
    signal = next(s for s in found if s.dimension == "caption_density")

    assert signal.confidence <= preference_cap(1)
    assert signal.safe_to_apply_automatically is False
    assert "below the 3 needed" in signal.why_not_safe


def test_disagreement_is_counted_rather_than_filtered_out(
    config, session, artifacts
):
    rate(config, session, artifacts, "li_danger", "good_callback",
         confidence=0.9)
    rate(config, session, artifacts, "li_react", "good_callback",
         confidence=0.9)
    rate(config, session, artifacts, "li_punch", "forced_callback",
         confidence=0.9)

    found = signals_module.extract(
        store_module.read_current(config, session.session_id))
    callbacks = next(s for s in found if s.dimension == "callbacks")
    assert callbacks.direction == "more"
    assert callbacks.evidence_count == 2
    assert callbacks.agreement == 1.0

    # The dissenting rating produced its own dimension rather than vanishing.
    assert any(s.dimension == "callback_naturalness" for s in found)


def test_an_unsure_rating_is_never_evidence_for_a_preference(
    config, session, artifacts
):
    rate(config, session, artifacts, "li_danger", "unsure")
    found = signals_module.extract(
        store_module.read_current(config, session.session_id))
    assert found == []


def test_a_timing_preference_is_never_automatically_safe(
    config, session, artifacts
):
    """Session 8's rule, from the other side: a marker is undoable, a cut is not."""
    for target in ("p_0", "p_1", "p_2", "p_3"):
        rate(config, session, artifacts, target, "boring",
             reasons=["pacing"], confidence=1.0)

    found = signals_module.extract(
        store_module.read_current(config, session.session_id))
    pace = next(s for s in found if s.dimension == "cut_pace")
    assert pace.evidence_count >= 4
    assert pace.confidence >= signals_module.SAFE_TO_APPLY_AT_OR_ABOVE
    assert pace.safe_to_apply_automatically is False
    assert "about timing" in pace.why_not_safe


def test_even_a_safe_looking_preference_says_nothing_reads_it(
    config, session, artifacts
):
    for target in ("li_danger", "li_react", "li_punch", "li_mark"):
        rate(config, session, artifacts, target, "good_caption",
             confidence=1.0)
    found = signals_module.extract(
        store_module.read_current(config, session.session_id))
    quality = next(s for s in found if s.dimension == "caption_quality")
    assert quality.safe_to_apply_automatically is True
    assert "nothing reads preference signals yet" in quality.why_not_safe


def test_a_preference_is_episode_scoped_until_it_spans_sessions(
    config, session, artifacts
):
    rate(config, session, artifacts, "li_danger", "good_caption")
    items = store_module.read_current(config, session.session_id)
    assert signals_module.extract(items)[0].scope == "episode"

    elsewhere = FeedbackItem.from_dict(items[0].to_dict())
    elsewhere.session_id = "another-session"
    elsewhere.feedback_id = "fb_elsewhere"
    spanning = signals_module.extract(items + [elsewhere])
    assert spanning[0].scope == "global"


def test_one_rating_cannot_vote_for_six_preferences(config, session, artifacts):
    item = rate(config, session, artifacts, "li_danger", "bad_caption",
                note="the danger caption is clickbait and hides the hud")
    assert len(signals_module.readings(item)) <= signals_module.MAX_PER_ITEM


# ---------------------------------------------------------------------------
# Part 6 -- training signals
# ---------------------------------------------------------------------------

def test_a_rated_decision_becomes_a_usable_training_signal(
    config, session, artifacts
):
    queue = queue_module.build(
        artifacts, session_id=session.session_id, limit=40)
    store_module.write_queue(config, session.session_id, queue)
    prompt = next(p for p in queue.prompts
                  if p.target.target_id == "li_danger")
    rate(config, session, artifacts, prompt.prompt_id, "good_caption",
         reasons=["caption"], confidence=0.9)

    found = training_module.extract(
        store_module.read_current(config, session.session_id),
        prompts={prompt.prompt_id: prompt}, timebase="roughcut",
    )
    signal = found[0]
    assert signal.usable_for_training is True
    assert signal.task == "caption_decision"
    assert signal.human_rating == "good_caption"
    assert signal.system_decision == prompt.system_decision
    assert signal.timebase == "roughcut"
    assert signal.weight > 0
    assert any(ref["id"] == "li_danger" for ref in signal.input_refs)
    assert signal.why and not signal.why_not


def test_the_task_follows_the_decision_not_just_the_record_type(
    config, session, artifacts
):
    """A caption and a punch-in are both ``LayerItem`` and different questions."""
    caption = rate(config, session, artifacts, "li_danger", "good_caption",
                   reasons=["caption"])
    zoom = rate(config, session, artifacts, "li_punch", "wrong_style",
                reasons=["visual"])
    assert training_module.task_for(caption) == "caption_decision"
    assert training_module.task_for(zoom) == "style_preference"

    hook = rate(config, session, artifacts, "hook_1", "bad_hook")
    assert training_module.task_for(hook) == "hook_selection"
    callback = rate(config, session, artifacts, "cb_1", "forced_callback")
    assert training_module.task_for(callback) == "callback_decision"
    asset = rate(config, session, artifacts, "ap_1", "bad_music_sfx")
    assert training_module.task_for(asset) == "asset_matching"
    finding = rate(config, session, artifacts, "f_1", "bad")
    assert training_module.task_for(finding) == "critique"


def test_a_measurable_correction_produces_a_before_and_an_after(
    config, session, artifacts
):
    rate(config, session, artifacts, "p_0", "shorten",
         correction="cut this shorter", correction_seconds=-5.0)
    signal = training_module.extract(
        store_module.read_current(config, session.session_id))[0]

    assert signal.has_before_after
    assert signal.before["duration"] == pytest.approx(30.0)
    assert signal.after["end"] == pytest.approx(25.0)
    assert signal.after["action"] == "shorten"


def test_a_direction_without_a_size_gets_a_before_and_no_after(
    config, session, artifacts
):
    rate(config, session, artifacts, "p_0", "shorten",
         correction="make it shorter")
    signal = training_module.extract(
        store_module.read_current(config, session.session_id))[0]
    assert signal.before and not signal.after
    assert signal.human_correction == "make it shorter"


def test_an_unusable_signal_is_emitted_with_its_reason(
    config, session, artifacts
):
    """Silently dropping it would hide what the collector is losing."""
    rate(config, session, artifacts, "whole", "unsure")
    found = training_module.extract(
        store_module.read_current(config, session.session_id))
    assert len(found) == 1
    assert found[0].usable_for_training is False
    assert found[0].weight == 0.0
    assert "unsure" in found[0].why_not


def test_feedback_with_no_recorded_system_decision_is_not_supervision(
    config, session, artifacts
):
    """An opinion about the video is not an opinion about a decision."""
    rate(config, session, artifacts, "200-260", "boring", reasons=["pacing"])
    signal = training_module.extract(
        store_module.read_current(config, session.session_id))[0]
    assert signal.usable_for_training is False
    assert "no system decision" in signal.why_not


def test_a_training_signal_round_trips_and_summarises(
    config, session, artifacts
):
    rate(config, session, artifacts, "li_danger", "good_caption")
    rate(config, session, artifacts, "whole", "unsure")
    found = training_module.extract(
        store_module.read_current(config, session.session_id))

    restored = TrainingSignal.from_dict(
        json.loads(json.dumps(found[0].to_dict())))
    assert restored.signal_id == found[0].signal_id
    assert restored.task in TASK_TYPES

    summary = training_module.summarise(found)
    assert summary["signals"] == 2
    assert summary["unusable"] == 1
    assert summary["blocked_because"]


# ---------------------------------------------------------------------------
# Part 7 -- exports
# ---------------------------------------------------------------------------

def test_a_jsonl_export_tags_every_row_with_its_kind(
    config, session, artifacts
):
    rate(config, session, artifacts, "li_danger", "too_much",
         reasons=["caption"])
    items = store_module.read_current(config, session.session_id)
    body, record = export_module.build(
        parts=["feedback", "preferences", "training"],
        items=items,
        preferences=signals_module.extract(items),
        training=training_module.extract(items),
        session=session.to_dict(),
    )
    rows = [json.loads(line) for line in body.splitlines() if line.strip()]
    kinds = [row["kind"] for row in rows]

    assert kinds[0] == "header"
    assert rows[0]["basis"] == NOT_MEASURED
    assert "feedback" in kinds and "training" in kinds
    assert record.counts["feedback"] == 1
    assert record.format == "jsonl"


def test_a_csv_export_says_it_is_lossy(config, session, artifacts):
    rate(config, session, artifacts, "li_danger", "too_much")
    items = store_module.read_current(config, session.session_id)
    body, record = export_module.build(
        parts=["feedback", "training"], fmt="csv", items=items,
        session=session.to_dict(),
    )
    header = body.splitlines()[0].split(",")
    assert "feedback_id" in header and "correction_text" in header
    assert record.parts == ["feedback"], "the other parts were dropped"
    assert "lossy" in record.notes


def test_an_unknown_export_format_is_refused():
    with pytest.raises(EditingError) as error:
        export_module.build(fmt="parquet")
    assert "jsonl" in error.value.hint


def test_an_export_is_written_with_a_manifest_and_never_overwritten(
    config, session, artifacts
):
    rate(config, session, artifacts, "li_danger", "good")
    items = store_module.read_current(config, session.session_id)

    paths = []
    for _ in range(2):
        body, record = export_module.build(
            items=items, session=session.to_dict())
        path, record = store_module.write_export(
            config, session.session_id, body=body, record=record,
            filename="feedback.jsonl")
        paths.append(path)

    assert paths[0] != paths[1], "a second export must not replace the first"
    assert paths[0].exists() and paths[1].exists()
    manifest = json.loads(
        (paths[0].parent / "feedback.manifest.json").read_text("utf-8"))
    assert manifest["checksum"] == record.checksum or manifest["checksum"]
    assert manifest["session_id"] == session.session_id
    assert manifest["basis"] == NOT_MEASURED
    assert len(store_module.list_exports(config, session.session_id)) == 2


# ---------------------------------------------------------------------------
# Part 8 -- reports
# ---------------------------------------------------------------------------

def test_the_report_leads_with_what_the_feedback_cannot_support(
    config, session, artifacts, pipeline_for
):
    pipeline = pipeline_for(config)
    queue = queue_module.build(
        artifacts, session_id=session.session_id, limit=20)
    store_module.write_queue(config, session.session_id, queue)
    rate(config, session, artifacts, "li_danger", "good_caption")
    rate(config, session, artifacts, "whole", "unsure")

    summary = pipeline.feedback_summary(session)
    text = feedback_report.render_report(summary)

    assert "## What this feedback cannot support" in text
    assert text.index("cannot support") < text.index("## What was said")
    assert NOT_MEASURED in text
    assert "1 of 2" in text
    assert "queued questions were answered" in text
    assert "Nothing has been trained" in text


def test_the_report_and_summary_are_written_where_the_review_lives(
    config, session, artifacts, pipeline_for
):
    pipeline = pipeline_for(config)
    rate(config, session, artifacts, "li_danger", "good")
    pipeline.feedback_summary(session)

    directory = store_module.session_dir(config, session.session_id)
    assert (directory / "summary.json").exists()
    assert (directory / "report.md").exists()
    saved = json.loads((directory / "summary.json").read_text("utf-8"))
    assert saved["counts"]["items"] == 1
    assert saved["basis"] == NOT_MEASURED


def test_a_report_on_an_empty_session_says_so(config, session, pipeline_for):
    summary = pipeline_for(config).feedback_summary(session)
    text = feedback_report.render_report(summary)
    assert "no feedback has been recorded" in text
    assert "Nothing consistent enough to name yet" in text


def _flat(text: str) -> str:
    """One line, single-spaced, so a wrapped banner is still findable."""
    return " ".join(str(text).split())


def test_the_queue_and_prompt_renderers_carry_the_disclaimer(artifacts):
    queue = queue_module.build(artifacts, limit=10)
    rendered = feedback_report.render_queue(queue)
    assert NOT_MEASURED in _flat(rendered)
    assert "WHAT THIS QUEUE COULD NOT ASK ABOUT" in rendered

    detail = feedback_report.render_prompt(queue.prompts[0])
    assert "WHAT THE SYSTEM DECIDED" in detail
    assert "WHY YOU ARE BEING ASKED" in detail
    assert "feedback rate" in detail


def test_one_item_renders_with_its_history(config, session, artifacts):
    first = rate(config, session, artifacts, "li_danger", "bad")
    second = rate(config, session, artifacts, "li_danger", "good_caption")
    history = store_module.read_all(config, session.session_id)
    text = feedback_report.render_item(
        second, history=store_module.history_of(history, second.target.key()))

    assert second.feedback_id in text
    assert first.feedback_id in text
    assert "EARLIER ON THIS TARGET" in text
    assert "WHAT HAPPENS TO THIS" in text


# ---------------------------------------------------------------------------
# Part 9 -- the pipeline seam
# ---------------------------------------------------------------------------

@pytest.fixture
def pipeline_for():
    def build(config):
        from editing.config import AudioConfig, SamplingConfig
        from editing.pipeline import build_pipeline

        pipeline = build_pipeline(
            config, SamplingConfig().validated(), AudioConfig().validated())
        pipeline.say = lambda message: None
        return pipeline
    return build


@pytest.fixture
def written(config, pipeline_for):
    """The same artifacts, on disk, so the pipeline loads them itself."""
    pipeline = pipeline_for(config)
    pipeline.write_rough_cut(a_rough_cut())
    pipeline.write_recommendations(some_recommendations())
    pipeline.write_layers(some_layers())
    pipeline.write_episode_memory(an_episode_memory())
    pipeline.write_retention_plan(a_retention_plan())
    return pipeline


def test_the_pipeline_loads_what_is_there_and_records_what_is_not(written):
    artifacts = written.feedback_artifacts()
    assert artifacts.sources["roughcut"] is True
    assert artifacts.sources["critique"] is False
    assert artifacts.style == "fast_funny"
    assert artifacts.sequence_name == SEQUENCE
    assert artifacts.timebase == "roughcut"


def test_start_then_queue_then_report_through_the_pipeline(written, config):
    session, queue = written.feedback_start(run_id="run_y", limit=10)
    assert queue is not None and len(queue.prompts) == 10
    assert store_module.queue_path(config, session.session_id).exists()

    artifacts = written.feedback_artifacts()
    written_item = collect_module.rate(
        config, session, artifacts, queue.prompts[0].prompt_id, "good")
    assert written_item.feedback_id

    summary = written.feedback_summary(session)
    assert summary["counts"]["items"] == 1
    assert summary["coverage"]["queued"] == 10
    assert summary["coverage"]["answered"] == 1


def test_the_pipeline_export_always_keeps_a_copy_with_the_review(
    written, config, tmp_path
):
    session, _queue = written.feedback_start(run_id="run_y", build_queue=False)
    artifacts = written.feedback_artifacts()
    collect_module.rate(config, session, artifacts, "li_danger", "good")

    elsewhere = tmp_path / "out" / "dataset.jsonl"
    target, record = written.feedback_export(session, out=str(elsewhere))

    assert target == elsewhere and elsewhere.exists()
    assert store_module.list_exports(config, session.session_id), (
        "the session keeps its own copy and manifest")


def test_the_estimate_creates_no_session(written, config):
    estimate = written.feedback_estimate()
    assert estimate["worth_reviewing"] > 0
    assert store_module.list_sessions(config) == []


# ---------------------------------------------------------------------------
# Part 10 -- nothing here needs a tool, a model or Premiere
# ---------------------------------------------------------------------------

def test_the_feedback_package_reaches_for_nothing_external():
    """Guards the promise in the module docstring, in one place.

    Every input to this layer is JSON another pass already wrote. If a module
    here ever imports the model client, FFmpeg or the Premiere bridge, the
    review stops working on a machine that has none of them -- which is most
    of the machines this will run on.
    """
    import importlib
    import inspect

    forbidden = ("editing.ffmpeg", "editing.visual.qwen",
                 "editing.premiere_link", "premiere")
    for name in ("schema", "store", "targets", "queue", "collect",
                 "signals", "training", "export", "report"):
        module = importlib.import_module(f"editing.feedback.{name}")
        source = inspect.getsource(module)
        for banned in forbidden:
            assert f"import {banned}" not in source, (name, banned)
            assert f"from {banned}" not in source, (name, banned)
